version: "3.8"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: malaria_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: root123
    command: --secure-file-priv=/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  web:
    build: .
    depends_on:
      - mysql
    env_file: .env
    ports:
      - "3000:3000"

volumes:
  mysql_data:
